docker run -it\
 -v "$(pwd):/home/app"\
 -p 4000:4000\
 -e PORT=4000\
 -e APP_URI=$APP_URI\
 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID\
 -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY\
 -e BACKEND_STORE_URI=$BACKEND_STORE_URI\
 -e ARTIFACT_STORE_URI=$ARTIFACT_STORE_URI\
 image_elon python app.py